config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/about' => 'pages#about', as: :pages_about
  resources :articles
  resources :categories

  devise_for :users
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_rich_text :content

  scope :filter_by_category, ->(params) { where(category_id: params[:cid]) if params[:cid].present? }
  # app/models/article.rb

  def self.search(params)
    if params[:q].present?
      return includes(:user).with_rich_text_content_and_embeds
               .where("LOWER(title) LIKE LOWER(?)", "%#{params[:q].to_s.squish}%")
               .order(id: :desc)
               .paginate(page: params[:page] || 1, per_page: 10)
    end

    includes(:user).with_rich_text_content_and_embeds
      .order(id: :desc)
      .paginate(page: params[:page] || 1, per_page: 10)
  end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]
  # GET /articles or /articles.json
  def index
    @articles = Article.all
    @category = Category.new
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :user_id, :active)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @articles = Article.search(params)
    @categories = Category.order(id: :desc)
  end

  def about
    @info = About.first
    @title = 'Ruby Dev'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # app/helpers/application_helper.rb
  def category_select_options
    Category.all.map { |c| [c.name, c.id] }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
	<div class="card">
		<div class="card-body">
			<h5 class="card-title text-primary">Title: <%= article.title %></h5>
			<p>
				<strong>User:</strong>
				<%= article.user_id %>
			</p>
			<p>
				<strong>Active:</strong>
				<%= article.active %>
			</p>
		</div>
	</div>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <!-- add hidden_field user_id here -->
  <%= form.hidden_field :user_id, value: current_user&.id %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-2">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="my-2">
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>
  <div class="my-2">
    <%= form.label :category_id, style: "display: block" %>
    <%= form.select :category_id, options_for_select(category_select_options, form.object.category&.id), { include_blank: "Select category"}, { class: 'form-select select2' } %>
  </div>
  <div class="my-2">
    <div class="form-check">
      <%= form.check_box :active, class: "form-check-input", class: "form-check-input" %>
      <%= form.label :active, class: "form-check-label" %>
    </div>
  </div>
  <div class="my-2">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
	<div class="row py-4">
		<div class="col-lg-6 text-danger">
			<h4>Articles</h4>
		</div>
		<div class="col-lg-6 text-end">
			<%= link_to "New article", new_article_path, class: 'btn btn-primary' %>
		</div>
	</div>
</div>
<div id="articles">
	<% @articles.each do |article| %>
		<%= render article %>
		<p class='py-2'>
			<%= link_to "Show", article, class: 'btn btn-secondary' %>
		</p>
	<% end %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
	<div class="card" style="width: 18rem;">
		<div class="card-body">
			<h5 class="card-title">Name: <%= category.name %></h5>
			<p>
				<strong>Description:</strong>
				<%= category.description %>
			</p>
		</div>
	</div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
	<div class="row py-4">
		<div class="col">
			<h1>Categories</h1>
		</div>
		<div class="col text-end">
			<%= link_to "New category", new_category_path, class: 'btn btn-primary' %>
		</div>
	</div>
</div>
<div id="categories">
	<% @categories.each do |category| %>
		<%= render category %>
		<p>
			<%= link_to "Show this category", category %>
		</p>
	<% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-muted py-5">
	<div class="container">
		<p class="float-end mb-1">
			<a href="/">Back to Home</a>
		</p>
		<p class="mb-1">Ruby on Rails</p>
		<p class="mb-1">Hotline: 0389141150 (Mr Son)</p>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="bd-header bg-dark py-3 d-flex align-items-stretch border-bottom border-dark">
	<div class="container-fluid d-flex align-items-center">
		<div class="d-flex flex-wrap justify-items-center align-items-center justify-content-md-between w-100">
			<h1 class="d-flex align-items-center fs-4 text-white mb-0">
				<img src="<%= image_path("son") %>" width="38" height="30" class="me-3" alt="Bootstrap">
				<div class="text-primary">SonBlog</div>
			</h1>
			<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
				<li><a href="/" class="nav-link px-2 text-white">Home</a></li>
				<li><a href="<%= categories_path %>" class="nav-link px-2 text-white">Category</a></li>
				<li><a href="<%= articles_path %>" class="nav-link px-2 text-white">Articles</a></li>
				<li><a href="<%= pages_about_path %>" class="nav-link px-2 text-white">About</a></li>
				<form class="d-flex text-end" role="search">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success" type="submit">Search</button>
				</form>
			</ul>
			<div class="text-end">
				<% if user_signed_in? %>
					<span class="text-white mx-2">
						<%= current_user.email %>
					</span>
					<%= link_to "Sign out", destroy_user_session_path, class: "btn btn-warning", data: { turbo_method: "delete" } %>
				<% else %>
					<%= link_to "Login", new_user_session_path, class: "btn btn-outline-light me-2" %>
					<%= link_to "Sign-up", new_user_registration_path, class: "btn btn-warning" %>
				<% end %>
			</div>
		</div>
	</div>
</header>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SonBlog</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
		<%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
	</head>
	<!-- app/views/layouts/application.html.erb -->
	<dialog id="turbo-confirm">
		<form method="dialog">
			<p>Are you sure?</p>
			<div>
				<button value="cancel">Cancel</button>
				<button value="confirm">Confirm</button>
			</div>
		</form>
	</dialog>
	<%= render  'layouts/header' %>
	<body>
		<div class="container">
			<% if notice.present? %>
				<div class="alert alert-primary mt-4" role="alert">
					<%= notice %>
				</div>
			<% end %>
			<% if alert.present? %>
				<div class="alert alert-danger mt-4" role="alert">
					<%= alert %>
				</div>
			<% end %>
			<%= yield %>
		</div>
	</body>
	<%= render  'layouts/footer' %>
</html>

app/views/pages/_article.html.erb
<div id="<%= dom_id article %>" class="mb-2">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= link_to article.title, article_path(article) %>
      </h5>
      <div class="card-text">
        <%= article.content %>
      </div>
      <p>
        <strong>Author:</strong>
        <%= article.user&.email %>
      </p>
    </div>
  </div>
</div>

app/views/pages/_category_item.html.erb
<div>
  <%= link_to category.name, root_path(cid: category.id, q: params[:q]), class: "#{params[:cid].to_i == category.id ? "fw-bold" : "text-decoration-none text-dark"}" %>
</div>

app/views/pages/_search_box.html.erb
<form action="<%= root_path %>">
  <div class="input-group">
    <input type="text" name="q" value="<%= params[:q] %>" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
    <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Search</button>
  </div>
  <div class="py-1">
    <span class="text-muted fs-6 fw-light">Found: <%= items.total_entries %></span>
  </div>
</form>

app/views/pages/about.html.erb
<div style="display: flex; flex-direction: column;">
	<div style="display: flex; flex: 1 1 auto; justify-content: center; align-items: center;">
		<h1 class='text-danger'><%= @title %></h1>
	</div>
	<ul>
		<li>Ten: <%= @info.ten %></li>
		<li>Nam sinh: <%= @info.nam_sinh %></li>
		<li>Dien thoai: <%= @info.dien_thoai %></li>
		<li>Dia chi: <%= @info.dia_chi %></li>
		<li>Tieu su: <%= @info.tieu_su %></li>
	</ul>
</div>

app/views/pages/home.html.erb
<div class="py-4">
  <%= render 'pages/search_box', items: @articles %>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3>Category</h3>
    <% @categories.each do |category| %>
      <%= render 'pages/category_item', category: category %>
    <% end %>
  </div>
  <div class="col-lg-8">
    <h3>Article</h3>
    <% unless @articles.present? %>
      <div class="alert alert-info" role="alert">
        <span>No items found. Please try agian!</span>
      </div>
    <% end %>
    <% @articles.each do |article| %>
      <%= render 'pages/article', article: article %>
    <% end %>
    <%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>